/**
 * US State capitals + basic info for the state info panel.
 * Used when a US state is clicked on the map.
 */

const US_STATE_INFO = {
  'Alabama': { capital: 'Montgomery', abbr: 'AL', timezone: 'UTC-6' },
  'Alaska': { capital: 'Juneau', abbr: 'AK', timezone: 'UTC-9' },
  'Arizona': { capital: 'Phoenix', abbr: 'AZ', timezone: 'UTC-7' },
  'Arkansas': { capital: 'Little Rock', abbr: 'AR', timezone: 'UTC-6' },
  'California': { capital: 'Sacramento', abbr: 'CA', timezone: 'UTC-8' },
  'Colorado': { capital: 'Denver', abbr: 'CO', timezone: 'UTC-7' },
  'Connecticut': { capital: 'Hartford', abbr: 'CT', timezone: 'UTC-5' },
  'Delaware': { capital: 'Dover', abbr: 'DE', timezone: 'UTC-5' },
  'Florida': { capital: 'Tallahassee', abbr: 'FL', timezone: 'UTC-5' },
  'Georgia': { capital: 'Atlanta', abbr: 'GA', timezone: 'UTC-5' },
  'Hawaii': { capital: 'Honolulu', abbr: 'HI', timezone: 'UTC-10' },
  'Idaho': { capital: 'Boise', abbr: 'ID', timezone: 'UTC-7' },
  'Illinois': { capital: 'Springfield', abbr: 'IL', timezone: 'UTC-6' },
  'Indiana': { capital: 'Indianapolis', abbr: 'IN', timezone: 'UTC-5' },
  'Iowa': { capital: 'Des Moines', abbr: 'IA', timezone: 'UTC-6' },
  'Kansas': { capital: 'Topeka', abbr: 'KS', timezone: 'UTC-6' },
  'Kentucky': { capital: 'Frankfort', abbr: 'KY', timezone: 'UTC-5' },
  'Louisiana': { capital: 'Baton Rouge', abbr: 'LA', timezone: 'UTC-6' },
  'Maine': { capital: 'Augusta', abbr: 'ME', timezone: 'UTC-5' },
  'Maryland': { capital: 'Annapolis', abbr: 'MD', timezone: 'UTC-5' },
  'Massachusetts': { capital: 'Boston', abbr: 'MA', timezone: 'UTC-5' },
  'Michigan': { capital: 'Lansing', abbr: 'MI', timezone: 'UTC-5' },
  'Minnesota': { capital: 'Saint Paul', abbr: 'MN', timezone: 'UTC-6' },
  'Mississippi': { capital: 'Jackson', abbr: 'MS', timezone: 'UTC-6' },
  'Missouri': { capital: 'Jefferson City', abbr: 'MO', timezone: 'UTC-6' },
  'Montana': { capital: 'Helena', abbr: 'MT', timezone: 'UTC-7' },
  'Nebraska': { capital: 'Lincoln', abbr: 'NE', timezone: 'UTC-6' },
  'Nevada': { capital: 'Carson City', abbr: 'NV', timezone: 'UTC-8' },
  'New Hampshire': { capital: 'Concord', abbr: 'NH', timezone: 'UTC-5' },
  'New Jersey': { capital: 'Trenton', abbr: 'NJ', timezone: 'UTC-5' },
  'New Mexico': { capital: 'Santa Fe', abbr: 'NM', timezone: 'UTC-7' },
  'New York': { capital: 'Albany', abbr: 'NY', timezone: 'UTC-5' },
  'North Carolina': { capital: 'Raleigh', abbr: 'NC', timezone: 'UTC-5' },
  'North Dakota': { capital: 'Bismarck', abbr: 'ND', timezone: 'UTC-6' },
  'Ohio': { capital: 'Columbus', abbr: 'OH', timezone: 'UTC-5' },
  'Oklahoma': { capital: 'Oklahoma City', abbr: 'OK', timezone: 'UTC-6' },
  'Oregon': { capital: 'Salem', abbr: 'OR', timezone: 'UTC-8' },
  'Pennsylvania': { capital: 'Harrisburg', abbr: 'PA', timezone: 'UTC-5' },
  'Rhode Island': { capital: 'Providence', abbr: 'RI', timezone: 'UTC-5' },
  'South Carolina': { capital: 'Columbia', abbr: 'SC', timezone: 'UTC-5' },
  'South Dakota': { capital: 'Pierre', abbr: 'SD', timezone: 'UTC-6' },
  'Tennessee': { capital: 'Nashville', abbr: 'TN', timezone: 'UTC-6' },
  'Texas': { capital: 'Austin', abbr: 'TX', timezone: 'UTC-6' },
  'Utah': { capital: 'Salt Lake City', abbr: 'UT', timezone: 'UTC-7' },
  'Vermont': { capital: 'Montpelier', abbr: 'VT', timezone: 'UTC-5' },
  'Virginia': { capital: 'Richmond', abbr: 'VA', timezone: 'UTC-5' },
  'Washington': { capital: 'Olympia', abbr: 'WA', timezone: 'UTC-8' },
  'West Virginia': { capital: 'Charleston', abbr: 'WV', timezone: 'UTC-5' },
  'Wisconsin': { capital: 'Madison', abbr: 'WI', timezone: 'UTC-6' },
  'Wyoming': { capital: 'Cheyenne', abbr: 'WY', timezone: 'UTC-7' },
  'District of Columbia': { capital: 'Washington, D.C.', abbr: 'DC', timezone: 'UTC-5' },
  'Puerto Rico': { capital: 'San Juan', abbr: 'PR', timezone: 'UTC-4' },
};

export default US_STATE_INFO;
